apiVersion: v1
kind: ConfigMap
metadata:
  name: webgoat-sidecar-nginx
  namespace: sqli
data:
  default.conf: |
    server {
      listen 8081;
      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8080;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx
  namespace: sqli
data:
  default.conf: |
    server {
      listen 8080;

      location /webgoat/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cookie_path /WebGoat /webgoat/WebGoat;
        proxy_pass http://webgoat:8081/;
      }

    }
